name: Send News Email

on:
  push:
    branches:
      - main
  # schedule:
  #   - cron: '0 * * * *' # Ini akan menjalankan pekerjaan setiap jam

jobs:
  send_email:
    runs-on: ubuntu-latest

    steps:
      - name: Fetch Technology News
        id: fetch_news
        run: |
          # Mengambil berita dari API dan menyimpannya dalam file news.json  
          response=$(curl -s "http://api.mediastack.com/v1/news?access_key=41b27600ad3b2fa9b947affa0e09bb36&categories=technology&languages=en")  
            
          # Mengambil judul, deskripsi, dan URL berita  
          news=$(echo $response | jq -r '.data | map("$$.title): $$.description) - $$.url)") | join("<br>")')  
          echo "news=$news" >> $GITHUB_ENV

      - name: Send Email
        uses: dawidd6/action-send-mail@v4
        with:
          server_address: smtp.gmail.com # Pastikan ini sesuai dengan pengaturan SMTP Anda
          server_port: 465
          secure: true
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: 'Berita Terbaru Teknologi'
          to: aessaputra@yahoo.com
          bcc: mail.aessaputra@gmail.com,aingmauuungg@gmail.com,cloud.aessaputra@gmail.com,contact.aessaputra@gmail.com,aessaputra@aol.com,aessaputra@proton.me,aessaputra@tuta.io,aessaputra@outlook.com,aessaputra407@gmail.com,foreveryours@outlook.sg
          from: 'Breaking News <${{ secrets.MAIL_USERNAME }}>'
          html_body: |
            <h2>Berita Terbaru di Bidang Teknologi:</h2>          
            <ul>          
              ${{ env.news }}          
            </ul>
