name: Email Advice

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'

jobs:
  send_email:
    runs-on: ubuntu-latest
    steps:
      - name: Get Advice
        id: get_advice
        run: |
          response=$(curl -s https://api.adviceslip.com/advice)                 
          advice=$(echo $response | jq -r '.slip.advice')      
          echo "advice=$advice" >> $GITHUB_ENV

      - name: Send Email
        uses: dawidd6/action-send-mail@v4
        with:
          server_address: smtp.gmail.com
          server_port: 465
          secure: true
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: 'Advice'
          to: aessaputra@yahoo.com
          from: 'Advice'
          html_body: |
            <h3 style="font-family: Arial, sans-serif; color: #4A4A4A;">🗣️ Advice</h3>      
            <p style="font-family: Arial, sans-serif; font-style: italic; font-size: 18px; color: #333; margin: 20px 0; border-left: 4px solid #BFA76D; padding-left: 15px; line-height: 1.5; background-color: #F9F9F9; border-radius: 5px; padding: 15px;">  
              "${{ env.advice }}"  
            </p>
